language: "en"

pipeline:
  - name: "SpacyNLP"
    model: "en_core_web_md"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "DIETClassifier"
    epochs: 50  # ✅ reduced to lower memory
  - name: "EntitySynonymMapper"

assistant_id: 20250128-211148-caramel-charge

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 50  # ✅ reduced
  - name: TEDPolicy
    max_history: 5
    epochs: 50
    constrain_similarities: true
