language: "en"  # Default language

pipeline:
- name: "SpacyNLP"
  model: "en_core_web_md"  # Default English model
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "DIETClassifier"
  epochs: 100

assistant_id: 20250128-211148-caramel-charge

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
